### ISSUE TITLE
.NET Standard issue

### ISSUE THREAD

**Issue by Dids** [voydz/souyuz#12]
I was wondering why my CI builds kept failing, then realized that while they worked fine in Xamarin Studio, they for some reason fail when building with souyuz, most likely due to an issue with .NET Standard libraries.

Could it also be an msbuild vs xbuild issue?

```
/Library/Frameworks/Mono.framework/Versions/4.8.1/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

	JsonExtensions.cs(13,81): error CS0012: The type `System.Object' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

**Comment by Dids** [comment]
It's pretty much this:
https://github.com/JamesNK/Newtonsoft.Json/issues/1260

That didn't really help though, as I'm not really sure why Xamarin Studio can compile it, but souyuz can't.

**Comment by Dids** [comment]
Just downgraded JSON .NET to 9.x, looks good so far, but doesn't feel like a long term/proper solution.
Still a bit fuzzy on the .NET Standard myself. :)

**Comment by johberd** [comment]
I'm not quite sure if this is an issue of souyuz per sé. There seems to be a general issue resolving NuGet dependencies, discussed [here](https://forums.xamarin.com/discussion/91208/number-of-packages-just-exploded-with-latest-newtonsoft-json-package-update).

I think the only solution so far is stick to 9.x, point out here:
https://github.com/JamesNK/Newtonsoft.Json/issues/1252#issuecomment-291021380

**Comment by Dids** [comment]
Fair point, closing this issue. :)

Thanks for the links, especially the first one. Never knew it had such a massive impact!
