### ISSUE TITLE
Zipping dSYM when targeting iPhoneSimulator/Release

### ISSUE THREAD

**Issue by Dids** [voydz/souyuz#14]
As part of my CI flow, I'm running UI tests in the iOS simulator as release builds.

Right now, souyuz isn't compatible with this, as it's trying to create a zip archive for MyApp.dSYM, which naturally doesn't exist for simulator builds.

Question is, is this a bug or a feature, and can I work around it?

**Comment by Dids** [comment]
I'm assuming this could be fixed [here](https://github.com/voydz/souyuz/blob/master/lib/souyuz/runner.rb#L93) by simply checking for the dSYM as early as possible, then bailing out if necessary, so something like this:
```ruby
return if not File.exists? Souyuz.cache[:build_dsym_path]
```

**Comment by Dids** [comment]
Looks like it's specifically happening with simulator builds, regardless if it's a debug or release build.

**Comment by voydz** [comment]
Hey there,

Yeah, I see your problem. Good catch, will have a look into this.

**Comment by Dids** [comment]
Just a heads up that this works as a temporary workaround:
```
sh("mkdir -p ../iOS/bin/iPhoneSimulator/Debug && touch ../iOS/bin/iPhoneSimulator/Debug/MyApp.app.dSYM")
```

**Comment by voydz** [comment]
Hey @Dids ,

can you try to update to 0.6.7? Should be fixed in this version.

Thanks

**Comment by Dids** [comment]
Yup, seems to work, thank you. :)
