### ISSUE TITLE
Increment version number

### ISSUE THREAD

**Issue by senart** [voydz/souyuz#18]
How does one auto increment the Version Number in an Android / iOS app with `souyuz`?

**Comment by voydz** [comment]
Hi,

please have a look at the example `fastfiles` in the wiki, see here https://github.com/voydz/souyuz/wiki. Especially the `app_version(options)` part. This is the action to modify version numbers. You can invoke the action like this:

```ruby
app_version(
  version: 'X.X'
  build: 'XX'
)
```

Using the lanes defined in the example fastfile you would increment version numbers like so:

```bash
# for android
fastlane android version version:X.X build:XX

# for ios
fastlane ios version version:X.X build:XX
```

Thanks for your interest in this project.

best regards,
Felix
