### ISSUE TITLE
Weird characters on build start

### ISSUE THREAD

**Issue by johberd** [voydz/souyuz#20]
I just mentioned some weird characters before the build starts:
```
[19:36:30]: ▸ 
Microsoft (R) Build Engine version 15.4.0.0 (master/f296e67b Wed Oct 25 12:26:03 EDT 2017) for Mono
[19:36:30]: ▸ Copyright (C) Microsoft Corporation. All rights reserved.
^[[24;15R[19:36:31]: ▸ Build started 1/29/2018 7:36:31 PM.
```
When I suppress logging by disabling the CommandExecutor printing, everything looks good.

**Comment by voydz** [comment]
Thanks for reporting, I will have a look on it soon.

best regards

**Comment by voydz** [comment]
@johannesberdin After observing this for the last few months, I've drawn the conclusion that these might come from `msbuild` directly? What is your thought? Did you have any updates on this issue?

Otherwise, I think we can close this issue.
