### ISSUE TITLE
set -o pipefail causes the build process to fail.

### ISSUE THREAD

**Issue by mserougi** [voydz/souyuz#26]
I've installed this plugin to use with Drone CI, the build process fails with "sh: 1: set: Illegal option -o pipefail" when trying to execute the following:

[12:07:53]: $ set -o pipefail && msbuild /p:Configuration=Release /p:SolutionDir=/drone/src/bitbucket.org/company/test-app/commits/33f665f98291013a5e17ecd09bec87cc638e6220/ /t:Build /t:SignAndroidPackage /drone/src/bitbucket.org/company/test-app/commits/33f665f98291013a5e17ecd09bec87cc638e6220/Droid/Test.Droid.csproj
[12:07:53]: ▸ sh: 1: set: Illegal option -o pipefail
sh: 1: set: Illegal option -o pipefail
[12:07:53]: Exit status: 2

Does the plugin need to include that in the build command?

**Comment by johberd** [comment]
Not sure if this is an issue of souyuz or rather the underlying Fastlane command executor but as long the build command is not using a pipeline we could remove the prefix.

I'm not familiar with Drone CI but is it possible to run the build process in bash shell; I think that should fix your problem.

**Comment by mserougi** [comment]
The build process is running in bash, this here is part of the script that's run by Drone CI:

```
#!/bin/bash

set -e

PARENT_DIRECTORY="$(pwd)"
mkdir $PARENT_DIRECTORY/android
ANDROID_DIR=$PARENT_DIRECTORY/android

apt-get update
apt-get install -y curl unzip

if ! java_loc="$(type -p "$java")" || [ -z "$java_loc" ]; then
  apt-get install -y openjdk-8-jdk
fi
  
echo ">> Install Android Environment"
# download android sdk
wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
unzip sdk-tools-linux-3859397.zip -d $ANDROID_DIR

yes | $ANDROID_DIR/tools/bin/sdkmanager --licenses
$ANDROID_DIR/tools/bin/sdkmanager --update
$ANDROID_DIR/tools/bin/sdkmanager "platforms;android-26" "build-tools;27.0.3"

echo ">> Install Mono"
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys insert_your_key
echo "deb http://download.mono-project.com/repo/ubuntu stable-xenial main" | tee /etc/apt/sources.list.d/mono-official-stable.list
apt-get update
apt-get install -y mono-complete

echo ">> Starting Fastlane environment = "$1
bundle exec fastlane $1
```

Is it possible to let the script that runs fastlane decide for itself if we need the pipefail option or not?

**Comment by voydz** [comment]
I am not familiar with drone either. But as @johannesberdin states; since we do not use pipelines, we can safely remove the prefix as such.

I will doublecheck and fix this issue ASAP.

regards
