### ISSUE TITLE
Can we use this plugin to build xamarin android projects?

### ISSUE THREAD

**Issue by hyper-venom** [voydz/souyuz#30]
Will I be able to build xamarin android projects using fastlane/fastlane-souyuz plugin?

**Comment by orestesgaolin** [comment]
yes, this is my sample step:

```
   souyuz(
        platform: "android",
        build_configuration: configuration",
        keystore_path: ENV["KEYSTORE_PATH"],
        keystore_alias: ENV["KEYSTORE_ALIAS"],
        keystore_password: ENV["KEYSTORE_PASSWORD"],
        output_path: "./src/App.Droid/bin/#{configuration}"
      )
```

**Comment by voydz** [comment]
@orestesgaolin thats exactly how you do it, thank you
closing here

**Comment by Kingamattack** [comment]
Hi i'm new with Fastlane and it's kind of hard to find where to start with Xamarin
I tool @orestesgaolin sample but the question is: What command i should type to make it works? 
Can i do it from anywhere on my local or only in my project? Thanks

**Comment by voydz** [comment]
Hey @Kingamattack to make use of this plugin you have to use fastlane, full documentation is located [here](https://docs.fastlane.tools/). But if you want to know how to use this plugin just have a look in the Wiki section of this repo [here](https://github.com/voydz/souyuz/wiki).There are example [Fastfiles](https://docs.fastlane.tools/advanced/Fastfile/) for [Android](https://github.com/voydz/souyuz/wiki/Fastfile-Example-for-Android) and [iOS](https://github.com/voydz/souyuz/wiki/Fastfile-Example-for-iOS).
