### ISSUE TITLE
How to sign multiple ABI apk files with Souyuz?

### ISSUE THREAD

**Issue by orestesgaolin** [voydz/souyuz#31]
I have separate .apk files for different ABIs i.e. 

- com.xxx.app-arm64-v8a.apk
- com.xxx.app-armeabi-v7a.apk

but souyuz signs only one .apk which is com.xxx..app.apk

```$  jarsigner -sigalg MD5withRSA -digestalg SHA1 -storepass "****" -keystore "****" -tsa http://timestamp.digicert.com -signedjar "./src/App.Droid/bin/Release/com.****.app.apk-unaligned" ./src/App.Droid/bin/Release/coml.****.app.apk ****```

Is it possible to sign also these two .apks?

**Comment by voydz** [comment]
Hey @orestesgaolin ,

this is currently not supported, but I am happy to accept pull requests. Sorry for responding that late, strange enough I am not notified if this repo gets a new issue.

best regards

**Comment by voydz** [comment]
closed since stale
