### ISSUE TITLE
keystore_alias_password?

### ISSUE THREAD

**Issue by aphex3k** [voydz/souyuz#33]
```
keystore_path: "{PATH_TO_YOUR_KEYSTORE}",
keystore_alias: "{ALIAS_OF_YOUR_KEYSTORE}",
keystore_password: "{YOUR_SUPER_SECRET_KEYSTORE_PASSWORD}"
```

This plugin only works if the password for the alias is the same as for the store file itself. If the password is different, souyuz just hangs.

**Comment by voydz** [comment]
Hey @aphex3k 

thanks for pointing this out. As I am very busy at the moment any pull request is much appreciated. The corresponding code to fix your issue is located here https://github.com/voydz/souyuz/blob/master/lib/souyuz/generators/java_sign_command_generator.rb

best regards

**Comment by aphex3k** [comment]
I guess I have to learn really ruby?!

**Comment by voydz** [comment]
closed since stale
