### ISSUE TITLE
Absolute_IPA_Path does not return absolute path

### ISSUE THREAD

**Issue by simonmartyr** [voydz/souyuz#6]
```
       absolute_ipa_path = File.expand_path(::Souyuz::Manager.new.work(values))
	
```

I've hit the issue recently that the script is only returning the ipa name rather than the full path. 
resulting in IPA can not be found error. 

I've worked around the issue like so:

```
::Souyuz::Manager.new.work(values)
absolute_ipa_path = File.join(values[:output_path], "#{values[:assembly_name]}.ipa") 
```

**Comment by voydz** [comment]
Thanks for the pull request #7, I am sorry that this takes so long to merge. I'll will have a look soon.

**Comment by johberd** [comment]
I cannot confirm that issue. I get an absolute path for `lane_context[SharedValues::IPA_OUTPUT_PATH]` running on El Captain, Ruby 2.3.3, latest fastlane, latest Xamarin.

@simonmartyr Can you provide more details where you experience the error?

**Comment by voydz** [comment]
I am closing this issue now. If anyone got further information, don't hesitate to reopen.
